name: CI

on:
  push:
    branches: [ Develop ]
  pull_request:
    branches: [ Develop ]
  workflow_dispatch:
    branches: [ Develop ]

jobs:
  analyze:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@master

    - name: Set XCode Version
      run: sudo xcode-select -s /Applications/Xcode_12.3.app

    - name: Xcodebuild Action
      uses: sersoft-gmbh/xcodebuild-action@v1.3
      with:
        project: RSSReader/RSSReader.xcodeproj
        scheme: RSSReader
        destination: platform=iOS Simulator,name=iPod touch (7th generation),OS=14.3
        action: analyze
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@master

    - name: Set XCode Version
      run: sudo xcode-select -s /Applications/Xcode_12.3.app

    - name: Xcodebuild Action
      uses: sersoft-gmbh/xcodebuild-action@v1.1
      with:
        project: RSSReader/RSSReader.xcodeproj
        scheme: RSSReader
        destination: platform=iOS Simulator,name=iPod touch (7th generation),OS=14.3
        action: build
  test:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@master

    - name: Set XCode Version
      run: sudo xcode-select -s /Applications/Xcode_12.3.app

    - name: Xcodebuild Action
      uses: sersoft-gmbh/xcodebuild-action@v1.1
      with:
        project: RSSReader/RSSReader.xcodeproj
        scheme: RSSReaderTests
        destination: platform=iOS Simulator,name=iPod touch (7th generation),OS=14.3
        action: test
